- linux-mingw/Dockerfile
- linux-mingw/mingw-setup.sh
See citra-emu/build-environments#22 for more details.
**Original description**:
Update the SDL2 version of the MinGW builds, as it is necessary for better controller support. See citra-emu/citra#5100.
> Set mingw SDL2 version to 2.0.10

- linux-mingw/Dockerfile
- linux-mingw/mingw-setup.sh
Reverts yuzu-emu/build-environments#5.
I need to take a look at this later. For now, this unblocks our Windows CI.
> Revert "Set mingw SDL2 version to 2.0.10"

- linux-flatpak/Dockerfile
Based on Citra's linux-flatpak Dockerfile ([here](https://github.com/citra-emu/build-environments/blob/master/linux-flatpak/Dockerfile)), abderrahim's flatpak Dockerfile from PR #4 and yuzu's linux-fresh Dockerfile ([here](https://github.com/yuzu-emu/build-environments/blob/master/linux-fresh/Dockerfile)).
Should be published as yuzuemu/build-environments:linux-flatpak
> Add Dockerfile for linux-flatpak

- linux-fresh/Dockerfile
- linux-mingw/Dockerfile
- linux-mingw/default
As a required change for https://github.com/yuzu-emu/yuzu/pull/3735 this updates the docker container to have additional dependencies installed through the package manager and through conan, that were previously vendored in the externals folder in yuzu. 
New system packages installed that were originally in externals:
* Boost - libboost-all-dev 
* Opus - libopus-dev 
* zstd - libzstd-dev 
* lz4 - liblz4-dev 
* zlib - zlib1g-dev 
* libzip - libzip-dev
New conan packages installed for the yuzu user:
* catch2/2.11.0
* fmt/6.2.0
* nlohmann_json/3.7.3
New misc packages added:
* python3-pip  - Needed to install conan
This PR also fixes up mingw cross compiling and sets up conan for cross compiling.
New system package installed for mingw:
* mingw-w64-boost 
* mingw-w64-lz4 
* mingw-w64-zlib 
* …
> Add new system libraries and install some additional libraries through conan

- linux-clang-format/Dockerfile
- linux-flatpak/Dockerfile
- linux-fresh/Dockerfile
- linux-mingw/Dockerfile
- linux-transifex/Dockerfile
This changes the script to use the `yuzu` user for anyone that runs the image. As a docker best practice, containers should try to only run as an unprivileged user https://docs.docker.com/engine/security/userns-remap/ to prevent privilege escalation attacks.
Also fixed a few small issues that crept in in the previous commits.
> Update the docker images to run as yuzu user (UID 1027)

- linux-clang-format/Dockerfile
This plays nicer with C++ attributes and is also more up to date.
Required for: https://github.com/yuzu-emu/yuzu/pull/4464
> linux-clang-format: Make use of clang-format 10

- linux-clang-format/Dockerfile
The actual [package](https://packages.ubuntu.com/focal/clang-format-10) itself has dropped the use of the decimal in the version number.
> clang-format: Correct package name

- linux-fresh/Dockerfile
Required for texture cache updates.
Also reorganizes the requirements list to be a little bit more alphabetized, and updates Conan packages.
> linux-fresh: Update to GCC 10.2

- linux-fresh/Dockerfile
- linux-mingw/Dockerfile
Add glslang and glslang-tools to linux-mingw and linux-fresh containers respectively. Required for TCR.
Also removes mbedtls dependency from linux-fresh as cleanup. Unneeded dependency leftover from Raptor.
> linux: Add glslang and glslang-utils to mingw and fresh containers

- linux-fresh/Dockerfile
Ubuntu 20.04's version of Boost (1.71.0) is older than yuzu's minimum requirement (1.73.0). Thus the container was downloading Boost through Conan each time it builds yuzu.
Instead, install Boost through Conan ahead of time, as opposed to installing effectively garbage.
> linux-fresh: Install Boost through Conan

- linux-fresh/Dockerfile
This is in preparation to have a legal AppImage when Ubuntu 16.04 is deprecated in April 2021. As stated in [AppImage's
documentation](https://docs.appimage.org/packaging-guide/distribution.html#appimagehub), to distribute yuzu on [AppImageHub](https://appimage.github.io/), an AppImage needs to compatible with the oldest still supported release of Ubuntu, which will be 18.04 in April.
Beyond making AppImages, this brings a number of other changes:
- The needed CMake, GCC, and Qt versions are now variables at the top of the Dockerfile.
- The dependencies list is sorted lexicographically.
- Added package `file`, required for the Qt linuxdeploy plugin, thus superseding #23.
- Added package `software-properties-common`, required to use `add-apt-repository`.
- Added package …
> linux-fresh: Downgrade to Bionic Beaver

- linux-fresh/Dockerfile
Adds nasm to linux-fresh so that FFmpeg can be compiled. ~~Removes mingw-w64-ffmpeg from linux-mingw to prevent packaging unused libraries with yuzu.~~ Holding off on mingw-w64-ffmpeg changes to avoid breaking things for now. I can roll that into a larger cleanup PR for linux-mingw later.
> linux-fresh: Add package nasm

- linux-fresh/Dockerfile
- linux-fresh/settings.yml
Adds the Clang compiler from apt.llvm.org to linux-fresh. The intention is to run two instances of linux-fresh when checking CI on yuzu, one compiles with GCC and the other with Clang.
This includes a workaround in Conan where the default configuration file is not set up to permit using Clang 12. settings.yml is there to allow using Clang 12.
Also moves `DEBIAN_FRONTEND=noninteractive` to its own environment variable entry to put an end to repeating the same text each time apt-get is used.
> linux-fresh: Add Clang 12 from llvm.org

- linux-fresh/Dockerfile
Adds the qt[version]wayland package to linux-fresh. Required to run the AppImage on Wayland.
> fresh: Add package qt(512)wayland

- linux-fresh/Dockerfile
Manually install Boost using a pre-built package. Works around an issue with the zlib Conan package failing to build with Clang.
This should also improve build times a tad.
> linux-fresh: Install Boost manually

- linux-fresh/Dockerfile
libhidapi-dev from Bionic repositories is too old for our needs. Download and install a binary package for hidapi manually from yuzu-emu/ext-linux-bin.
This adds a number of packages required to compile hidapi. Needed for producing new hidapi packages in the future.
Lastly, remove Conan package installation at this stage: CMake will just download them again when we build yuzu, so no point in doing it twice.
> fresh: Add hidapi 0.10.1 from ext-linux-bin

- linux-mingw/Dockerfile
This opts to not install the yuzu dependencies from Conan, since this happens again at build time regardless of installing them here.
Also prevents removing the `/tmp` directory entirely, to not break building packages later (such as libusb).
> linux-mingw: Remove Conan packages

- linux-mingw/Dockerfile
We don't use them, no reason to keep them. Removes mingw-w64-ffmpeg -- it never worked, and we no longer use it. And we don't use python2 any more.
In addition, apply a fix to the container: Dockerhub's old version of Docker has an issue that causes pacman to fail. Based on https://github.com/lxqt/lxqt-panel/pull/1562
Saves about 2.3 GB from the finished container.
> mingw: Delete 32 bit binaries and fix container

- .github/workflows/ci.yml
This pull request will migrate the Docker container building infrastructure to GitHub Actions.
Docker Hub now does not provide a free CI option even for FOSS projects now.
> CI: switch to use GitHub Actions

- linux-mingw/Dockerfile
- linux-mingw/settings.yml
Defers to our own repo for MinGW libraries of Qt 5.15, fmt, and zstd. Required to build yuzu in a manner that does not crash.
> mingw: Use ext-linux-bin for select packages

- linux-fresh/Dockerfile
- linux-mingw/Dockerfile
Initially intended to just refresh the containers so they can update their root certificates. This also updates linux-fresh to Qt 5.15.2 since EA AppImages are dead in the middle of the sea and I'm tired of waiting on that to get 5.15 out.
> fresh,mingw: Refresh and update to Qt 5.15.2

- linux-transifex/Dockerfile
This fixes the build failing because of the following reasons:
1. GitHub Actions uses its own user inside the container, so the container should not include the USER directive.
2. Newer Docker builder systems (BuilderX) will not accept the MAINTAINER directive.
A huge thanks to @liushuyu for helping me figure this out and providing the explanation.
> linux-transifex: Remove user and maintainer directives

- linux-fresh/Dockerfile
This is a future-proof measure so that the binaries will stay compatible with Ubuntu 18.04 instead of whatever CI image the upstream uses.
> linux-fresh: install glslang and hidapi from PPA

- linux-mingw/Dockerfile
ccache requires a newer version of glibc than could be provided with the Azure workaround. Revert 87c73e5b5d2dee97bef8d1ef6c17c610872a22a7 so that ccache will work.
This may not work with Azure. If that is the case, we will need to revert ccache to an earlier build.
> mingw: Remove glibc workaround

- linux-fresh/Dockerfile
- linux-fresh/qtconcurrentthreadengine.patch
- linux-fresh/settings.yml
The intention was to get Clang 14 and GCC 11 going, and AppImage verification tools on it, but I ended up cleaning quite a bit more than that.
Beyond those mentioned, this:
- removes some packages that were too old to build yuzu with,
- removes FFmpeg packages since using it breaks the AppImage,
- installs tools needed to build yuzu with [Polly](https://polly.llvm.org) and possibly [ThinLTO](https://clang.llvm.org/docs/ThinLTO.html) (Mainline would probably timeout with LTO, though),
- fixes savoury1 PPAs so that glslang would install once again,
- [patches](https://codereview.qt-project.org/c/qt/qtbase/+/339417/2/src/concurrent/qtconcurrentthreadengine.h) the Qt 5.15 header that causes GCC 11 build issues,
- and updates Boost to 1.79.0.
> linux-fresh: Update to Clang 14, GCC 11, and misceallaneous

- linux-mingw/Dockerfile
- linux-mingw/default
- linux-mingw/settings.yml
Removes usage of packages from our own repo since the upstream ones are no longer broken. Some packages were AUR-only, so they are now built at the end of the script. Also adds zstd and libusb yuzu requirements.
In addition, adds clang, polly, and lld as well as mingw-w64-clang, a wrapper of Clang for building projects as a Windows target.
> mingw: Clang preparation

- linux-fresh/Dockerfile
- linux-mingw/Dockerfile
Deprecates Conan usage. For fresh, we install vcpkg and all the packages we need from it/Conan. Catch2 must be built and installed separately because Microsoft made it difficult to install a specific version of a package.
In linux-mingw, we just update a comment and install nlohmann-json for MinGW. We were already extremely close to not needing an external package manager here. We do not install vcpkg because it barely works on a Linux host targeting x64-mingw. From https://vcpkg.io/en/docs/users/mingw.html:
> MinGW is not tested as part of vcpkg repository's CI process, so regressions can occur as part of library updates.
Supersedes #53 -- I rolled that change into this PR simply to avoid rebasing.
Supersedes #56
> fresh,mingw: Deprecate Conan for vcpkg

- linux-mingw/Dockerfile
Fixes build issues with Arch's SDL 2.24.0. We aren't trying to upgrade that high a version of SDL2 at the moment, anyway.
Closes #59
> mingw: Revert to SDL 2.0.20

- linux-fresh/Dockerfile
Limits vcpkg to installing a specific set of package versions, such as fmt 9.0.0. Prevents it from updating package versions beyond our control.
> fresh: Specify vcpkg version

- linux-liftinstall/Dockerfile
Creates a Docker container that is minimally capable of building the liftinstall for Linux.
Note that it is not strictly necessary to push a build of this container to Docker Hub, since I'm not aware of any CI that we do on yuzu-emu/liftinstall.
> liftinstall: Add liftinstall container script

- linux-fresh/Dockerfile
Required for yuzu-emu/yuzu#9300
3.22 was chosen because:
- @Morph1984 requested at least 3.20
- only 3.17 and later includes [7e9b9fe9](https://gitlab.kitware.com/cmake/cmake/-/commit/7e9b9fe918cde6d0769ade833b2086c1d89c45ff), required in the aforementioned PR
- Ubuntu 22.04 ships 3.22
> fresh: Increase CMake version to 3.22.6

- linux-fresh-arm64/Dockerfile
Tested and able to build yuzu using the regular linux script, with -DYUZU_TESTS=OFF added (due to unsatsifyable older Catch2 dependency)
> fresh-arm64: add linux-fresh-arm64

- linux-fresh/Dockerfile
- linux-fresh/gcc_build_requirements
Requires yuzu-emu/ext-linux-bin#12
Ubuntu bionic loses support next month, so we are getting ahead of it by upgrading to Ubuntu 20.04 (focal) now.
Notable changes include reorganizing the initial swath of packages to indicate where their necessity originated, updating Boost and GCC to their latest versions, and installing the latest version of GNU Binutils.
This was spurred on by yuzu-emu/yuzu#9982 exposing the fact we have a relatively old version of GNU as running on linux-fresh.
> fresh: Update container to Ubuntu focal

- linux-fresh-arm64/Dockerfile
- linux-mingw/Dockerfile
Requires yuzu-emu/ext-linux-bin#13
For MinGW, we install a Boost package I generated on my machine using https://aur.archlinux.org/packages/mingw-w64-boost. This is because trying to build the package during container building does not succeed: `mingw-w64-boost` has the build dependency `mingw-w64-wine` which adds considerable bloat to the image.
In fresh-arm64, we pin vcpkg's version to the most recent version before Boost 1.80 was added. This fortunately still includes fmt 9.0.0.
> Install Boost 1.79 for mingw, fresh-arm64

- linux-transifex/Dockerfile
Adds the FFmpeg package libavfilter-dev, needed by yuzu-emu/yuzu#10283.
Also moves all the packages and individual commands to their own lines, and sorts the packages alphabetically.
> transifex: Add libavfilter-dev

- linux-mingw/Dockerfile
Recent Arch Linux packaging policy changes require Python modules to
be installed through the package manager, not pip.
pip is still installed for compatibility with existing docker scripts
on yuzu's side.
> mingw: Install pefile through pacman
